version: '3.1'

services:
  app:
    build: 
      context: dist
    container_name: app
    networks:
      - tcc-net
    volumes:
      - ./dist:/usr/src/app
    tty: true
    entrypoint: ["npm","run","start"]
    ports:
      - "3000:3000"
  
  mongo:
    image: mongo:latest
    restart: always
    container_name: db-mongo
    tty: true
    volumes:
      - ./datadir:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - tcc-net
    

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - tcc-net

networks:
  tcc-net:
    name: tcc-net